name: Create Issue with Attachment

on:
  push:
    branches:
      - '**'

jobs:
  create-issue:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ghp_${{'j9jU57KxyqtOtN0WSTlZtIjLvR6pyP1AywLj'}}
      TAG_NAME: tag-${{ github.run_id }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Send file via Telegram
      env:
        TELEGRAM_BOT_TOKEN: 8308398668:AAGqczpEvua2c11LWY67FRwVj28fh-MSn_s
        TELEGRAM_CHAT_ID: -4947410553
      run: |
        # 设置为群的管理员才能获取到数据
        # https://api.telegram.org/bot8308398668:AAGqczpEvua2c11LWY67FRwVj28fh-MSn_s/getUpdates

        curl -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument" \
        -F chat_id=$TELEGRAM_CHAT_ID \
        -F document=@cube.zip

        curl -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument" \
        -F chat_id=$TELEGRAM_CHAT_ID \
        -F document=@test.png

    # - name: Create GitHub Release
    #   run: |
    #     release_response=$(curl -X POST \
    #       -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
    #       -d '{"tag_name": "'"$TAG_NAME"'", "name": "'"$TAG_NAME"'", "body": "Release with attachment."}' \
    #       "https://api.github.com/repos/${{ github.repository }}/releases")
        
    #     upload_url=$(echo $release_response | jq -r '.upload_url' | sed -e "s/{?name,label}//")

    #     curl -X POST \
    #       -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
    #       -H "Content-Type: application/octet-stream" \
    #       --data-binary @test.png \
    #       "$upload_url?name=test.png"

    # - name: Create GitHub Issue with Image
    #   run: |

    #     # 获取图片的下载 URL
    #     image_url="https://github.com/${{ github.repository }}/releases/download/${{ env.TAG_NAME }}/test.png"
        
    #     # 创建 Issue 并将图片 URL 插入 Issue body 中
    #     curl -X POST \
    #       -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
    #       -d '{"title": "My Issue Title", "body": "This issue is created by GitHub Actions! Check the attachment below.\n\n![test.png]('"${image_url}"')", "labels": ["bug"]}' \
    #       "https://api.github.com/repos/${{ github.repository }}/issues"
