name: Create Issue with Attachment

on:
  push:
    branches:
      - '**'

jobs:
  create-issue:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ghp_${{'j9jU57KxyqtOtN0WSTlZtIjLvR6pyP1AywLj'}}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create GitHub Release
      run: |
        unique_tag="v1-${{ github.run_id }}"

        release_response=$(curl -X POST \
          -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
          -d '{"tag_name": "'"$unique_tag"'", "name": "'"$unique_tag"'", "body": "Release with attachment."}' \
          "https://api.github.com/repos/${{ github.repository }}/releases")
        
        upload_url=$(echo $release_response | jq -r '.upload_url' | sed -e "s/{?name,label}//")

        curl -X POST \
          -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @test.png \
          "$upload_url?name=test.png"

    - name: Create GitHub Issue with Image
      run: |
        # 获取图片的下载 URL
        image_url="https://github.com/${{ github.repository }}/releases/download/v1.0/test.png"
        
        # 创建 Issue 并将图片 URL 插入 Issue body 中
        curl -X POST \
          -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
          -d '{"title": "My Issue Title", "body": "This issue is created by GitHub Actions! Check the attachment below.\n\n![test.png]('"${image_url}"')", "labels": ["bug"]}' \
          "https://api.github.com/repos/${{ github.repository }}/issues"
