name: Create Issue with Attachment

on:
  push:

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Upload zip file to GitHub Artifact
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -F "file=@/path/to/your/file.zip" \
          "https://uploads.github.com/repos/${{ github.repository }}/actions/artifacts/${{ github.run_id }}/zip"

    - name: Create GitHub Issue
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"title": "My Issue Title", "body": "This issue is created by GitHub Actions! Check the attachment.", "labels": ["bug"]}' \
          "https://api.github.com/repos/${{ github.repository }}/issues"
