name: macOS Screenshot

on:
  push:
    paths:
      - '.github/workflows/demo.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    # runs-on: macos-13
    runs-on: macos-latest

    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: displayplacer
        run: |
          brew install displayplacer
          
          displays=$(displayplacer list)
          echo "$displays"

          # 提取 Persistent screen id
          display_id=$(echo "$displays" | grep -o 'Persistent screen id: [^ ]*' | awk '{print $4}' | head -n 1)

          if [ -n "$display_id" ]; then
            echo "当前显示器 ID: $display_id"
            displayplacer "id:$display_id res:1920x1080"
          else
            echo "未找到显示器 ID"
          fi

      - name: Write to frpc.toml
        shell: bash
        run: |
          cat << EOF > frpc.toml
          user = "mac-mini"

          serverAddr = "165.154.244.104"
          serverPort = 7000
          loginFailExit = true

          auth.method = "token"
          auth.token = "2f1d3a0e-9b64-4b91-b76b-8cb4a2f2e5d3"

          webServer.addr = "127.0.0.1"
          webServer.port = 7400
          webServer.user = "admin"
          webServer.password = "admin"

          [[proxies]]
          name = "vnc"
          type = "tcp"
          localIP = "127.0.0.1"
          localPort = 5900
          remotePort = 5900
          EOF

          sudo sysadminctl -addUser newuser -password password
          sudo dscl . -append /Groups/admin GroupMembership newuser
          # dscl . -read /Groups/admin GroupMembership

          # brew install socat
          # socat TCP-LISTEN:1234,fork TCP:127.0.0.1:5900 &
          
          chmod +x ./frpc-$(uname -m)
          ./frpc-$(uname -m) -c frpc.toml &
          
          # sleep 5
          # curl -u admin:admin http://127.0.0.1:7400/api/status

      - name: frpc
        shell: bash
        run: |
          brew install cliclick
          brew install tesseract
          # brew install tesseract-lang

          mkdir -p images

          recognize_and_click() {
            local left=$1
            local top=$2
            local width=$3
            local height=$4
            local target_text=$5
            local max_wait_time=${6:-30}  # 默认最大等待时间为30秒

            for ((i=1; i<=max_wait_time; i++)); do
              screencapture -C -x -R${left},${top},${width},${height} images/screenshot.png

              # 使用tesseract识别截图中的文字
              recognized_text=$(tesseract images/screenshot.png -)

              # 如果识别到目标文本，模拟点击区域中心
              local center_x=$((left + width / 2))
              local center_y=$((top + height / 2))

              if [[ "$recognized_text" == *"$target_text"* ]]; then
                echo "识别到目标文本 '$target_text'，正在点击..."
                cliclick -m verbose c:$(($center_x)),$(($center_y))
                return 0
              fi

              sleep 1
              echo "未识别到目标文本 '$target_text'，已等待 $i 秒..."
            done

            echo "未在 $max_wait_time 秒内识别到目标文本 '$target_text'，退出。"
            return 1
          }

          while true; do
            if recognize_and_click 847 430 226 26 "Allow" 1; then
                echo "点击成功，退出循环"
                break
            fi

            rand_x=$((RANDOM % 1920))
            rand_y=$((RANDOM % 1080))
            echo "随机移动到 $rand_x,$rand_y"
            cliclick -m verbose m:${rand_x},${rand_y}

            sleep 1
          done

          cliclick -m verbose c:28,14
          sleep 2
          screencapture -C -x images/screenshot_0.png

          echo 系统设置
          cliclick -m verbose c:47,75
          sleep 2
          screencapture -C -x images/screenshot_1.png
          
          echo 输入区域
          cliclick -m verbose c:710,196
          sleep 1
          cliclick -m verbose dc:710,196
          screencapture -C -x images/screenshot_2.png
          echo 输入中...
          cliclick -m verbose t:"Screen Sharing"
          echo 输入结束
          sleep 5
          screencapture -C -x images/screenshot_3.png

          echo 共享
          cliclick -m verbose c:666,316
          sleep 2
          screencapture -C -x images/screenshot_4.png

          echo 开启
          cliclick -m verbose c:1240,343
          sleep 2
          screencapture -C -x images/screenshot_5.png

          echo 关闭
          cliclick -m verbose c:517,190
          screencapture -C -x images/screenshot_6.png

          recognize_and_click 966 434 110 28 "Share Screen" 120

      - name: 上传
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: images/*

      - name: 等待
        run: |
          # sleep 1
          sleep 14400
