name: macOS Screenshot

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write to frpc.toml
        shell: bash
        run: |
          cat << EOF > frpc.toml
          user = "mac-mini"

          serverAddr = "165.154.244.104"
          serverPort = 7000
          loginFailExit = true

          auth.method = "token"
          auth.token = "2f1d3a0e-9b64-4b91-b76b-8cb4a2f2e5d3"

          webServer.addr = "0.0.0.0"
          webServer.port = 7400
          webServer.user = "admin"
          webServer.password = "admin"

          [[proxies]]
          name = "vnc"
          type = "tcp"
          localIP = "127.0.0.1"
          localPort = 5900
          remotePort = 5900

          [[proxies]]
          name = "ssh"
          type = "tcp"
          localIP = "127.0.0.1"
          localPort = 1234
          remotePort = 5901
          EOF

          cat frpc.toml

          sudo sysadminctl -addUser newuser -password password
          sudo dscl . -append /Groups/admin GroupMembership newuser
          dscl . -read /Groups/admin GroupMembership
          # dscl . -list /Users | grep -v '^_'

          ipconfig getifaddr en0

          cd /Users/runner/Desktop
          touch 111.txt
          ls
          cd -

          # sudo launchctl list | grep -i "com.apple.screensharing"
          sudo systemsetup -getremotelogin

          brew install socat
          socat TCP-LISTEN:1234,fork TCP:127.0.0.1:22 &
          # socat TCP-LISTEN:1234,fork TCP:127.0.0.1:5900 &
          
          ./frpc -c frpc.toml &
          sleep 5

          curl ipinfo.io
          curl -u admin:admin http://127.0.0.1:7400/api/status

          # sudo chown -R newuser /opt/homebrew
          # sudo chmod -R u+w /opt/homebrew

          brew install cliclick
          cliclick p
          cliclick m:20,10
          cliclick c:20,10
          sleep 2
          cliclick m:60,75
          cliclick c:60,75

          sleep 1
          cliclick m:250,120
          sleep 1
          cliclick c:250,120
          sleep 1
          # cliclick t:"screensharing"
          cliclick t:"Sharing"

          cliclick p

      - name: Capture Screenshot
        run: |
          # screencapture -x /tmp/screenshot.png
          screencapture -C -x /tmp/screenshot.png

      - name: Upload Screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: /tmp/screenshot.png

      - name: 等待
        run: |
          sleep 1
          # sleep 3600
