on:
  # push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKER_USERNAME: sophia66756
  DOCKER_PASSWORD: pat_Z_E6fMPlXDKQwjkDkWcd0k18qKM

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: dckr_${{ env.DOCKER_PASSWORD }}

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            dev:
              - 'Dockerfile'
              - '.github/workflows/dev.yml'

      - name: build
        if: steps.changes.outputs.dev == 'true'
        run: |
          docker build . \
            --build-arg IP=47.243.69.11,47.76.85.88,8.210.147.180 \
            -t ${{ env.DOCKER_USERNAME }}/ubuntu

          docker push ${{ env.DOCKER_USERNAME }}/ubuntu
