name: 并发测试2025

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: Asia/Shanghai

jobs:
  concurrent-jobs:
    runs-on: self-hosted
    strategy:
      matrix:
        job_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - name: 记录时间戳
        shell: bash
        run: |
          curl ipinfo.io
          sudo docker ps
          sudo docker images

      - name: 停止
        run: |
          sudo docker kill ci-runner
