name: 测试

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# run-name: '${{ inputs.os }} ${{ inputs.port }}'

env:
  TZ: Asia/Shanghai

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 测试
        run: |
          for i in {1..4}; do 
            (
              IP="70.36.96.$i"

              # 创建测量
              ID=$(curl -s -X POST "https://api.globalping.io/v1/measurements" \
                -H "Content-Type: application/json" \
                -d "{
                  \"target\": \"$IP\",
                  \"type\": \"ping\",
                  \"measurementOptions\": { \"packets\": 4 }
                }" | jq -r '.id')

              # 轮询直到测量完成
              while true; do
                RESPONSE=$(curl -s "https://api.globalping.io/v1/measurements/$ID")
                STATUS=$(echo "$RESPONSE" | jq -r '.status')
                echo $IP $STATUS
                if [[ "$STATUS" == "finished" ]]; then
                  echo "$RESPONSE" | jq .
                  break
                fi
                sleep 1
              done
            ) &
          done

          # 等待所有后台任务完成
          wait
