on:
  push:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  job:
    # uses: mirllan2025/express/.github/workflows/main.yml@master
    # with:
    #   ip: ${{inputs.ip}}

    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v4

      - name: 测试
        run: |
          REPO_NAME=$(gh api 'user/repos?sort=created&direction=desc&per_page=1' --jq '.[0].full_name')
          echo REPO_NAME=$REPO_NAME

          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
            "https://api.github.com/repos/$REPO_NAME/actions/workflows/test.yml/dispatches" \
            -d '{
              "ref": "main",
              "inputs": {
                "ip": "192.168.0.123"
              }
            }'
