on:
  push:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  job:
    # uses: mirllan2025/express/.github/workflows/main.yml@master
    # with:
    #   ip: ${{inputs.ip}}

    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v4

      - name: 测试
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/test.yml/dispatches" \
            -d '{
              "ref": "main",
              "inputs": {
                "ip": "192.168.0.123"
              }
            }'
