name: 测试

on:
  workflow_dispatch:
    inputs:
      subnet:
        description: '要测试的子网 (例如: 70.36.96)'
        required: true
        default: '70.36.96'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: Asia/Shanghai

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 测试
        run: |
          echo "## Ping 成功的 IP" >> $GITHUB_STEP_SUMMARY

          for i in {1..250}; do 
            (
              IP="${{ inputs.subnet }}.$i"

              # 创建测量
              ID=$(curl -s -X POST "https://api.globalping.io/v1/measurements" \
                -H "Content-Type: application/json" \
                -d "{
                  \"target\": \"$IP\",
                  \"type\": \"ping\",
                  \"measurementOptions\": { \"packets\": 4 }
                }" | jq -r '.id')

              # 轮询直到测量完成
              while true; do
                RESPONSE=$(curl -s "https://api.globalping.io/v1/measurements/$ID")
                STATUS=$(echo "$RESPONSE" | jq -r '.status')
                echo $IP $STATUS
                if [[ "$STATUS" == "finished" ]]; then
                  LOSS=$(echo "$RESPONSE" | jq -r '.results[0].result.stats.loss')
                  if [[ "$LOSS" -lt 100 ]]; then
                    echo "$IP $LOSS" >> results.txt
                  fi
                  break
                fi
                sleep 1
              done
            ) &
          done

          wait

          if [[ -f results.txt ]]; then
            # 按 IP 最后一段排序
            sort -t. -k4,4n results.txt | while read IP LOSS; do
              echo "- $IP (丢包率: ${LOSS}%)" >> $GITHUB_STEP_SUMMARY
            done
            SUCCESS_COUNT=$(wc -l < results.txt)
          else
            SUCCESS_COUNT=0
          fi

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 总成功数: $SUCCESS_COUNT" >> $GITHUB_STEP_SUMMARY
