on:
  push:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  job:
    # uses: mirllan2025/express/.github/workflows/main.yml@master
    # with:
    #   ip: ${{inputs.ip}}

    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v4

      - name: 测试
        env:
          GH_TOKEN: ghp_${{'q7kvPczAPsdVaKwwzQoZPJAlL02MLh2PCKTC'}}
        run: |
          # REPO_NAME=$(gh api 'user/repos?sort=created&direction=desc&per_page=1' --jq '.[0].full_name')
          # echo REPO_NAME=$REPO_NAME

          USERNAME=$(gh api user --jq .login)
          MY_REPO="$USERNAME/express"

          if gh repo view $MY_REPO &>/dev/null; then
            echo "仓库 $MY_REPO 已存在，正在删除..."
            gh repo delete $MY_REPO --yes
          fi

          gh repo fork mirllan2025/express --clone

          gh api \
            -X PUT \
            /repos/$MY_REPO/actions/permissions \
            -F enabled=true \
            -F allowed_actions=all

          cd express
          ls

          # gh workflow run test.yml \
          #   --repo "$REPO_NAME" \
          #   --ref main \
          #   --field subnet=70.36.100



          # REPO_NAME=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          #   "https://api.github.com/user/repos?sort=created&direction=desc&per_page=1" \
          #   | jq -r '.[0].full_name')
          # echo REPO_NAME=$REPO_NAME

          # curl -X POST \
          #   -H "Accept: application/vnd.github+json" \
          #   -H "Authorization: Bearer $GITHUB_TOKEN" \
          #   "https://api.github.com/repos/$REPO_NAME/actions/workflows/test.yml/dispatches" \
          #   -d '{
          #     "ref": "main",
          #     "inputs": {
          #       "subnet": "70.36.100"
          #     }
          #   }'
