name: macOS 测试

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos-14:
    runs-on: macos-14

    steps:
      - name: macos-14
        run: |
          uname -m

  macos-latest:
    runs-on: macos-latest

    steps:
      - name: macos-latest
        run: |
          uname -m
